apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://example.com/your-repo.git
    path: ui
    targetRevision: HEAD
  project: default
