apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-app
  namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://example.com/your-repo.git
    path: crossplane
    targetRevision: HEAD
  project: default
